Fix failure on Destructor and Qualified Name lookup
trail-of-forks/llvm-project pull request #16
Opened 2024-04-28 16:36 UTC by kumarak

2024-04-28 16:39 UTC, kumarak commented on clang/lib/AST/DeclarationName.cpp
> +  OS << N.getAsOpaquePtr() << "\t";
This needs to go. Its from debug loh

2024-04-28 17:20 UTC, pgoodman requested changes

2024-04-28 17:20 UTC, pgoodman commented on clang/lib/AST/DeclarationName.cpp
> +      return Record;
`->getCanonicalDeclaration()`?

2024-04-28 17:20 UTC, pgoodman commented on clang/lib/AST/DeclarationName.cpp
> +    return Ty.getAsOpaquePtr();
I would try doing something like `Ty.dump();`, especially if you have a small unit test, just to see what's getting through.

2024-05-04 18:53 UTC, pgoodman approved these changes

2024-05-04 18:53 UTC, merged